name: flutter_coolweather
description: CoolWeather Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  flutter_swiper: ^1.1.6
  flutter_slidable: ^0.5.4
  dio: ^3.0.9
  pull_to_refresh: ^1.5.8
  intl_translation: ^0.17.5
  cached_network_image: ^2.1.0
  shared_preferences: ^0.5.7+3
  package_info: ^0.4.1
  modal_progress_hud: ^0.1.3
  provider: ^4.1.3
  flutter_screenutil: ^1.1.0
  flutter_easyrefresh: ^2.1.1
  flutter_custom_dialog: ^1.0.20
  # flutter路由
  fluro: ^1.6.3
  # 图片查看器
  photo_view: ^0.10.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  video_player:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/nodata.png
    - assets/images/loading.png
    - assets/images/bg1.jpg
    - assets/images/bg2.jpg
    - assets/images/weather/100.png
    - assets/images/weather/101.png
    - assets/images/weather/102.png
    - assets/images/weather/103.png
    - assets/images/weather/104.png
    - assets/images/weather/150.png
    - assets/images/weather/153.png
    - assets/images/weather/154.png
    - assets/images/weather/300.png
    - assets/images/weather/301.png
    - assets/images/weather/302.png
    - assets/images/weather/303.png
    - assets/images/weather/304.png
    - assets/images/weather/305.png
    - assets/images/weather/306.png
    - assets/images/weather/307.png
    - assets/images/weather/308.png
    - assets/images/weather/309.png
    - assets/images/weather/310.png
    - assets/images/weather/311.png
    - assets/images/weather/312.png
    - assets/images/weather/313.png
    - assets/images/weather/314.png
    - assets/images/weather/315.png
    - assets/images/weather/316.png
    - assets/images/weather/317.png
    - assets/images/weather/318.png
    - assets/images/weather/399.png
    - assets/images/weather/350.png
    - assets/images/weather/351.png
    - assets/images/weather/400.png
    - assets/images/weather/401.png
    - assets/images/weather/402.png
    - assets/images/weather/403.png
    - assets/images/weather/404.png
    - assets/images/weather/405.png
    - assets/images/weather/406.png
    - assets/images/weather/407.png
    - assets/images/weather/408.png
    - assets/images/weather/409.png
    - assets/images/weather/410.png
    - assets/images/weather/499.png
    - assets/images/weather/456.png
    - assets/images/weather/457.png
    - assets/images/weather/500.png
    - assets/images/weather/501.png
    - assets/images/weather/502.png
    - assets/images/weather/503.png
    - assets/images/weather/504.png
    - assets/images/weather/507.png
    - assets/images/weather/508.png
    - assets/images/weather/509.png
    - assets/images/weather/510.png
    - assets/images/weather/511.png
    - assets/images/weather/512.png
    - assets/images/weather/513.png
    - assets/images/weather/514.png
    - assets/images/weather/515.png
    - assets/images/weather/900.png
    - assets/images/weather/901.png
    - assets/images/weather/999.png



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
